import argparse
import random
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATASET_DIR = PROJECT_ROOT / "datasets" / "Pedestrian Obstacle Detection.v6-for-validation.yolov11"
OUTPUT_DIR = PROJECT_ROOT / "training" / "roboflow_pedestrian_obstacles_split"

CLASS_NAMES = [
    "animal",
    "barrier",
    "bike",
    "crosswalk",
    "hazard-sign",
    "person",
    "pole",
    "stairs",
    "stall",
    "vehicle",
]


def paired_images(dataset_dir: Path) -> list[Path]:
    image_dir = dataset_dir / "valid" / "images"
    label_dir = dataset_dir / "valid" / "labels"

    if not image_dir.exists() or not label_dir.exists():
        raise FileNotFoundError(
            f"Expected Roboflow export at {dataset_dir} with valid/images and valid/labels"
        )

    images = sorted(
        p for p in image_dir.iterdir() if p.suffix.lower() in {".jpg", ".jpeg", ".png"}
    )
    return [p for p in images if (label_dir / f"{p.stem}.txt").exists()]


def write_lines(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_data_yaml(output_dir: Path) -> None:
    names = "\n".join(f"  {idx}: {name}" for idx, name in enumerate(CLASS_NAMES))
    data_yaml = f"""# Generated by training/prepare_roboflow_split.py
train: {output_dir.resolve().as_posix()}/train.txt
val: {output_dir.resolve().as_posix()}/val.txt
test: {output_dir.resolve().as_posix()}/test.txt

nc: {len(CLASS_NAMES)}
names:
{names}
"""
    (output_dir / "data.yaml").write_text(data_yaml, encoding="utf-8")


def create_split(
    dataset: Path = DATASET_DIR,
    output: Path = OUTPUT_DIR,
    seed: int = 42,
    train_fraction: float = 0.8,
    val_fraction: float = 0.1,
) -> None:
    dataset = dataset.resolve()
    output = output.resolve()

    if (
        not 0 < train_fraction < 1
        or not 0 < val_fraction < 1
        or train_fraction + val_fraction >= 1
    ):
        raise ValueError("train and val fractions must sum to less than 1")

    images = paired_images(dataset)
    if not images:
        raise RuntimeError(f"No paired images/labels found in {dataset}")

    rng = random.Random(seed)
    rng.shuffle(images)

    train_end = int(len(images) * train_fraction)
    val_end = train_end + int(len(images) * val_fraction)

    splits = {
        "train": images[:train_end],
        "val": images[train_end:val_end],
        "test": images[val_end:],
    }

    output.mkdir(parents=True, exist_ok=True)
    for split_name, split_images in splits.items():
        lines = [p.resolve().as_posix() for p in split_images]
        write_lines(output / f"{split_name}.txt", lines)

    write_data_yaml(output)

    print(f"Created split at {output}")
    for split_name, split_images in splits.items():
        print(f"{split_name}: {len(split_images)} images")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create deterministic train/val/test lists from the Roboflow validation export."
    )
    parser.add_argument("--dataset", type=Path, default=DATASET_DIR)
    parser.add_argument("--output", type=Path, default=OUTPUT_DIR)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--train", type=float, default=0.8)
    parser.add_argument("--val", type=float, default=0.1)
    args = parser.parse_args()

    create_split(args.dataset, args.output, args.seed, args.train, args.val)


if __name__ == "__main__":
    main()
